In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('../input/triple_systems.csv')
data.head()

,pl_name,hostname,sy_snum,sy_pnum,pl_orbper,pl_orbsmax,pl_rade,pl_bmasse,pl_orbeccen,pl_eqt,st_spectype,st_teff,st_rad,st_mass,sy_dist,sy_vmag
0,16 Cyg B b,16 Cyg B,3,1,798.500000,1.6600,13.50,565.737400,0.680,NaN,G3 V,5750.0,1.13,1.080,21.13970,6.21500
1,51 Eri b,51 Eri,3,1,9100.000000,10.4000,NaN,3464.329636,0.570,807.0,F0 IV,7422.0,1.45,1.750,29.75750,5.21149
2,91 Aqr b,91 Aqr,3,1,181.400000,0.7000,13.10,1017.000000,0.027,NaN,K0 III,4665.0,11.00,1.400,44.03040,4.23946
3,BD-14 3065 b,BD-14 3065 A,3,1,4.288973,0.0656,21.59,3932.000000,0.066,2001.0,NaN,6935.0,2.35,1.410,589.42300,11.10000
4,GJ 229 A c,GJ 229,3,2,121.932680,0.3840,2.87,8.581367,0.366,NaN,M1.5V,3564.0,0.46,0.509,5.75624,8.15000

In [3]:
planet_data = data.copy()
planet_data = planet_data.drop(['hostname'], axis=1)
planet_data = planet_data.drop(['sy_snum'], axis=1)
planet_data = planet_data.drop(['sy_pnum'], axis=1)
planet_data = planet_data.drop(['st_spectype'], axis=1)
planet_data = planet_data.drop(['st_teff'], axis=1)
planet_data = planet_data.drop(['st_rad'], axis=1)
planet_data = planet_data.drop(['st_mass'], axis=1)
planet_data = planet_data.drop(['sy_vmag'], axis=1)

planet_data.head()

,pl_name,pl_orbper,pl_orbsmax,pl_rade,pl_bmasse,pl_orbeccen,pl_eqt,sy_dist
0,16 Cyg B b,798.500000,1.6600,13.50,565.737400,0.680,NaN,21.13970
1,51 Eri b,9100.000000,10.4000,NaN,3464.329636,0.570,807.0,29.75750
2,91 Aqr b,181.400000,0.7000,13.10,1017.000000,0.027,NaN,44.03040
3,BD-14 3065 b,4.288973,0.0656,21.59,3932.000000,0.066,2001.0,589.42300
4,GJ 229 A c,121.932680,0.3840,2.87,8.581367,0.366,NaN,5.75624

In [4]:
planet_data.to_csv('../output/planets_triples.csv')

---

In [1]:
1e-4

0.0001

In [5]:
triples = pd.read_csv("../input/final_triples.csv")
triples

,Sustav,Orbitalna konfiguracija,Oznaka matične zvijezde,Ime zvijezde A,Ime zvijezde B,Ime zvijezde C,Masa A [m_s],Masa B [m_s],Masa C [m_s],Radijus A [R_s],...,i_u [º],Omega_u [º],omega_u [º],Oznake vanjskog para,a_v [AU],e_v,i_v [º],Omega_v [º],omega_v [º],Izvori
0,Gliese 667,S(C),C,Gliese 667 A,Gliese 667 B,Gliese 667 C,0.730,0.690,0.310,0.760,...,127.600,133.200,68.100,AB-C,230.0,NaN,NaN,NaN,NaN,"[14], [17], [18], [19], [20]"
1,LTT 1445,S(A),A,LTT 1445 A,LTT 1445 B,LTT 1445 C,0.257,0.215,0.161,0.271,...,89.640,137.630,209.000,A-BC,34.0,NaN,NaN,NaN,NaN,"[14], [17], [20], [21], [22]"
2,94 Ceti,S(A),A,94 Ceti A,94 Ceti B,94 Ceti C,1.300,0.550,0.340,1.898,...,108.323,191.496,334.895,A-BC,220.0,0.260,104.0,97.0,342.000,"[14], [17], [19], [23], [24], [25]"
3,Kepler-444,S(A),A,Kepler-444 A,Kepler-444 B,Kepler-444 C,0.754,0.307,0.296,0.753,...,NaN,NaN,NaN,A-BC,52.2,0.550,85.4,250.7,227.300,"[14], [17], [19], [20], [26]"
4,HD 132563,S(C),C,HD 132563 Aa,HD 132563 Ab,HD 132563 B,1.081,0.600,1.010,1.300,...,NaN,NaN,160.200,AB-C,400.0,NaN,NaN,NaN,NaN,"[14], [17], [19], [20], [27], [28]"
5,WASP-12,S(A),A,WASP-12 A,WASP-12 B,WASP-12 C,1.430,0.380,0.370,1.660,...,NaN,NaN,NaN,A-BC,450.0,NaN,NaN,NaN,NaN,"[14], [17], [19], [20], [29], [30]"
6,GJ 229,S(A),A,Gliese 229 A,Gliese 229 Ba,Gliese 229 Bb,0.581,37.700,33.400,0.549,...,31.400,210.400,3.200,A-BC,42.9,0.736,47.7,168.3,358.285,"[17], [31], [32]"
7,GJ 900 A,S(ABC)-P,ABC,GJ 900 A,GJ 900 B,GJ 900 C,0.670,0.340,0.240,0.716,...,82.210,NaN,109.800,A-BC,20.0,NaN,NaN,NaN,NaN,"[17], [19], [33]"
8,HAT-P-8,S(A),A,HAT-P-8 A,HAT-P-8 B,HAT-P-8 C,1.270,0.220,0.180,1.490,...,NaN,NaN,NaN,A-BC,217.0,NaN,NaN,NaN,NaN,"[14], [17], [19], [20], [29], [34]"
9,HD 65216,S(A),A,HD 65216 A,HD 65216 Ba,HD 65216 Bb,0.950,0.090,0.080,0.864,...,NaN,NaN,NaN,A-BC,255.0,NaN,NaN,NaN,NaN,"[14], [17], [19], [20], [35]"

In [6]:
systems = triples["Sustav"].dropna().astype(str)

planet_data = planet_data.loc[
    planet_data["pl_name"].fillna("").astype(str).apply(
        lambda name: systems.apply(lambda system: system in name).any()
    )
]

planet_data

,pl_name,pl_orbper,pl_orbsmax,pl_rade,pl_bmasse,pl_orbeccen,pl_eqt,sy_dist
4,GJ 229 A c,121.932680,0.38400,2.870000,8.581367,0.3660,NaN,5.75624
5,GJ 229 b,579.474950,1.08600,3.970000,14.937935,0.4040,NaN,5.75624
16,HAT-P-8 b,3.076340,0.04496,15.692600,406.822400,0.0000,1713.0,211.55300
26,HD 132563 b,1544.000000,2.62000,13.600000,473.547000,0.2200,NaN,105.15500
38,HD 65216 b,577.600000,1.30100,13.600000,411.589850,0.2700,NaN,35.12050
39,HD 65216 c,5370.000000,5.75000,13.400000,645.194900,0.1700,NaN,35.12050
47,Kepler-444 b,3.600105,0.04178,0.403000,0.037400,0.1600,938.0,36.43960
48,Kepler-444 c,4.545884,0.04881,0.497000,0.079300,0.3100,868.0,36.43960
49,Kepler-444 d,6.189392,0.06000,0.530000,0.200000,0.1800,783.0,36.43960
50,Kepler-444 e,7.743493,0.06960,0.546000,0.100000,0.1000,727.0,36.43960
51,Kepler-444 f,9.740486,0.08110,0.741000,0.332000,0.2900,673.0,36.43960
53,LTT 1445 A b,5.358764,0.03810,1.340000,2.730000,0.1800,431.0,6.86929
54,LTT 1445 A c,3.123903,0.02661,1.147000,1.540000,0.2230,508.0,6.86929
66,WASP-12 b,1.091419,0.02340,22.025647,467.210100,0.0447,2601.0,427.24600

In [7]:
planet_data.to_csv("../output/final_exoplanets.csv")